# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pytorchse3',
                'doc_host': 'https://vivekg.dev',
                'git_url': 'https://github.com/eigenvivek/pytorchse3',
                'lib_path': 'pytorchse3'},
  'syms': { 'pytorchse3.core': {'pytorchse3.core.foo': ('core.html#foo', 'pytorchse3/core.py')},
            'pytorchse3.se3': { 'pytorchse3.se3.se3_exp_map': ('se3.html#se3_exp_map', 'pytorchse3/se3.py'),
                                'pytorchse3.se3.se3_log_map': ('se3.html#se3_log_map', 'pytorchse3/se3.py'),
                                'pytorchse3.se3.taylor_A': ('se3.html#taylor_a', 'pytorchse3/se3.py'),
                                'pytorchse3.se3.taylor_B': ('se3.html#taylor_b', 'pytorchse3/se3.py'),
                                'pytorchse3.se3.taylor_C': ('se3.html#taylor_c', 'pytorchse3/se3.py')},
            'pytorchse3.so3': { 'pytorchse3.so3.cross_product_matrix': ('so3.html#cross_product_matrix', 'pytorchse3/so3.py'),
                                'pytorchse3.so3.so3_log_map': ('so3.html#so3_log_map', 'pytorchse3/so3.py')}}}
